apps/noticias/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    path('', Main, name='main'),
    path('nosotros/', nosotros, name='nosotros'),
    path('constance/', login_required(CosntanceView.as_view()), name='constance'),

    path('publicacion/<int:pk>/', publicacion_view, name='publicacion'),
    path('createpublicaion/', login_required(CreatePublicacionView.as_view()), name='create_publicacion'),
    path('updatepublicaion/<int:pk>/', login_required(UpdatePublicaionView.as_view()), name='update_publicaion'),
    path('listpublicacion/', login_required(ListPublicacionView.as_view()), name='list_publicacion'),
    path('archivoinline/<int:pk>/', login_required(archivo_inline_view), name='archivo_inline'),
    path('search/', ListPublicacionBusquedaView.as_view(), name='search'),

    path('listpaginas/', login_required(ListPaginasView.as_view()), name='list_paginas'),
    path('createpagina/', login_required(CreatePaginaView.as_view()), name='create_pagina'),
    path('updatepagina/<int:pk>/', login_required(UpdatePaginaView.as_view()), name='update_pagina'),

    path('listtipo/', login_required(ListTiposView.as_view()), name='list_tipo'),
    path('createtipo/', login_required(CreateTipoView.as_view()), name='create_tipo'),
    path('updatetipo/<int:pk>/', login_required(UpdateTipoView.as_view()), name='update_tipo'),

    path('listdepartemento/', login_required(ListDepartamentoView.as_view()), name='list_departamento'),
    path('creardeparatmento/', login_required(CreateDepartamentoView.as_view()), name='create_departamento'),
    path('updatedepartamento/<int:pk>/', login_required(UpdateDepartamentoView.as_view()), name='update_departamento'),

    path('listautoridades/', login_required(ListAutoridadesView.as_view()), name='list_autoridades'),
    path('createautoridades/', login_required(CreateAutoridadesView.as_view()), name='create_autoridaes'),
    path('updateautoridaes/<int:pk>/', login_required(UpdateAutoridadesView.as_view()), name='update_autoridades'),

    path('listfiltropublicacion/<int:pk>/', ListPublicacionFiltroBusquedaView.as_view(), name='list_filtro_publicacion')
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView
from .views import *

urlpatterns = [
    path('login/',
        LoginView.as_view(template_name='auth/login.html'),
        name='login'
    ),
    path('logout/',
        logout_then_login,
        name='logout'
    ),
]

planipage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.urls import reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url=reverse_lazy('noticias:main')), name='home'),
    path('noticias/', include(('apps.noticias.urls','noticias'), namespace='noticias')),
    path('users/', include(('apps.users.urls','users'), namespace='users')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/noticias/models.py
from django.db import models
from django.db.models import Q

# Create your models here.

class Autoridades(models.Model):
	nombre = models.CharField(
		max_length=500,
		null=False,
		blank=False
	)
	cargo = models.CharField(
		max_length=500
	)
	prioridad = models.FloatField(
		null=False,
		blank=False,
		default=1
	)
	class Meta:
		ordering = ['prioridad','id']
	def __str__(self):
		return self.nombre

class Pagina(models.Model):
	nombre = models.CharField(
		null=False,
		blank=False,
		max_length=200
	)
	url = models.URLField(
		null=False,
		blank=False
	)
	def __str__(self):
		return self.nombre

class Departamento(models.Model):
	nombre = models.CharField(
		null=False,
		blank=False,
		max_length=200
	)
	prioridad = models.FloatField(
		null=False,
		blank=False,
		default=1
	)
	destacar = models.BooleanField(
		null=False,
		blank=False,
		default=False
	)
	class Meta:
		ordering = ['prioridad','id']
	def tipos_get(self):
		return Tipo.objects.filter(departamento=self)
	def __str__(self):
		return self.nombre

class Tipo(models.Model):
	departamento = models.ForeignKey('noticias.Departamento', on_delete=models.CASCADE)
	tipo = models.CharField(
		null=False,
		blank=False,
		max_length=300
	)
	prioridad = models.FloatField(
		null=False,
		blank=False,
		default=1
	)
	class Meta:
		ordering = ['prioridad','id']
	def __str__(self):
		return str(self.departamento) + ' - ' + self.tipo

class Publicacion(models.Model):
	tipo = models.ManyToManyField('noticias.Tipo')
	nombre = models.CharField(
		null=False,
		blank=False,
		max_length=500
	)
	resumen = models.CharField(
		null=True,
		blank=True,
		max_length=500
	)
	contenido = models.TextField(
		null=False,
		blank=False
	)
	publicar = models.BooleanField(
		null=False,
		blank=False,
		default=False
	)
	creado = models.DateTimeField(
		null=False,
		blank=False,
		auto_now_add=True,
	)
	modificado = models.DateTimeField(
		null=False,
		blank=False,
		auto_now=True,
	)
	def solo_fotos(self):
		return Archivo.objects.filter(Q(archivo__icontains='.jpeg')|Q(archivo__icontains='.jpg')|Q(archivo__icontains='.png'), publicacion=self)
	def archivos(self):
		return Archivo.objects.filter(~(Q(archivo__icontains='.jpeg')|Q(archivo__icontains='.jpg')|Q(archivo__icontains='.png')),  publicacion=self)
	def __str__(self):
		return self.nombre

class Archivo(models.Model):
	publicacion = models.ForeignKey('noticias.Publicacion', on_delete=models.CASCADE)
	archivo = models.FileField(
		upload_to='archivos/%Y-%m-%d-%H-%i-%s-%u/',
		null=False,
		blank=False
	)
	prioridad = models.FloatField(
		null=False,
		blank=False,
		default=1
	)
	def __str__(self):
		return str(self.publicacion)

templates/base/base_form.html
{% extends "base/center_body.html" %}
	{% block contend %}
		<div class="card">
			<div class="card-header">
				{% block name %}
					
				{% endblock name %}
			</div>
			<div class="card-body">
				{% block bodyform %}
					
				{% endblock bodyform %}
			</div>
		</div>
		{% block extra %}
			
		{% endblock extra %}
	{% endblock contend %}

templates/base/base_list.html
{% extends "base/center_body.html" %}
	{% block contend %}
		<div class="card">
			<div class="card-header">
				{% block name %}
					
				{% endblock name %}
			</div>
			<div class="card-body">
				{% block bodylist %}
					
				{% endblock bodylist %}
			
				{% if is_paginated %}
					<div class="d-flex justify-content-center">
						<ul class="pagination">
							{% if page_obj.has_previous %}
							    <li class="page-item">
									<a class="page-link" href="?page={{ page_obj.previous_page_number }}
									{% if request.GET %}
										{% for key, value in request.GET.items %}
											{% if key != 'page' %}
												&{{key}}={{value}}
											{% endif %}
										{% endfor %}
									{% endif %}">Anterior</a>
								</li>
							{% endif %}
							    <li  class="page-item disabled">
							        <a class="page-link " href="#">{{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</a>
							    </li>
							{% if page_obj.has_next %}
							    <li class="page-item">
									<a class="page-link" href="?page={{ page_obj.next_page_number }}
									{% if request.GET %}
										{% for key, value in request.GET.items %}
											{% if key != 'page' %}
												&{{key}}={{value}}
											{% endif %}
										{% endfor %}
									{% endif %}">Siguiente</a>
							    </li>
							{% endif %}
						</ul>
					</div>
				{% endif %}
			</div>
		</div>	
	{% endblock contend %}

templates/base/base_main.html
{% load static %}
<!doctype html>
<html>
	<head>

		<!-- Required meta tags -->
		<meta charset="utf-8">
		<!-- Chrome, Firefox OS and Opera -->
		<meta name="theme-color" content="#101010">
		<!-- Windows Phone -->
		<meta name="msapplication-navbutton-color" content="#101010">
		<!-- iOS Safari -->
		<meta name="description" content="Pagina principal de la direccion de planificacion universitaria UATF" />
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Google tag (gtag.js) -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-3NJXM405CD"></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());

			gtag('config', 'G-3NJXM405CD');
		</script>
		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/2.4.0/css/lg-thumbnail.min.css" integrity="sha512-GRxDpj/bx6/I4y6h2LE5rbGaqRcbTu4dYhaTewlS8Nh9hm/akYprvOTZD7GR+FRCALiKfe8u1gjvWEEGEtoR6g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
		<script src="https://kit.fontawesome.com/9328387887.js" crossorigin="anonymous"></script>
		<script type="text/javascript" src="{% static "noframework.waypoints.min.js" %}"></script>
		<link rel="stylesheet" href="{% static "styles.css" %}">
		<script src="https://cdn.tiny.cloud/1/r5mk10z5ioaut7wydr1emkbv2zj7wqyyiytek82v372sfolz/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

		<title>Dirección de Planificación Universitaria - UATF</title>
	</head>
	<body>

		{% block navbar %}
			{% include "base/nav_var.html" %}	
		{% endblock navbar %}

		{% block body %}
			
		{% endblock body %}

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

		{% block scripts %}
			
		{% endblock scripts %}
	</body>
</html>

templates/base/center_body.html
{% extends "base/base_main.html" %}
	{% block body %}
		<div class="pt-5 pb-5">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-md-12">
						{% block contend %}
							
						{% endblock contend %}
					</div>
				</div>
			</div>
		</div>
	{% endblock body %}

templates/base/nav_var.html
{% load static %}
<nav id="marca" class="navbar fixed-top navbar-expand-lg navbar-dark color-primary">
	<div class="container-fluid">
		<a class="navbar-brand" href="/">
			<img src="{% static "logo.svg" %}" alt="Bootstrap" height="24">
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link" aria-current="page" href="{% url 'noticias:nosotros' %}">Nosotros</a>
				</li>
				{% if request.paginas %}
					
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						Paginas De Interés
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
							{% for p in request.paginas %}
								<li><a class="dropdown-item" target="_blank" href="{{p.url}}"><i class="fas fa-link"></i> {{ p.nombre }}</a></li>
							{% endfor %}
						</ul>
					</li>
					
				{% endif %}
				{% if request.departamentos %}
					{% for dep in request.departamentos %}
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							{% if dep.destacar %}
								<span class="parpadea"><strong>{{dep.nombre}}</strong>
							{% else %}
								{{dep.nombre}}
							{% endif %}
							</a>
							<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
								{% for tip in dep.tipo_set.all %}
									<li><a class="dropdown-item" href="{% url 'noticias:list_filtro_publicacion' tip.id %}"><i class="fas fa-list"></i> {{ tip.tipo }}</a></li>
								{% endfor %}
							</ul>
						</li>
					{% endfor %}
				{% endif %}
				
				{% if request.user.is_authenticated %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						Administración
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
							<li><a class="dropdown-item" href="{% url 'noticias:create_pagina' %}">Crear Pagina</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:list_paginas' %}">Lista de Paginas</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:create_departamento' %}">Crear Departamento</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:list_departamento' %}">Lista de Departamentos</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:create_tipo' %}">Crear Tipo</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:list_tipo' %}">Lista de Tipos</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:create_publicacion' %}"></i> Crear Publicacion</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:list_publicacion' %}">Lista de Publicaciones</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:create_autoridaes' %}">Crear Autoridad</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:list_autoridades' %}">Lista de Autoridades</a></li>
							<li><a class="dropdown-item" href="{% url 'noticias:constance' %}">Constantes</a></li>
						</ul>
					</li>
				{% endif %}
			</ul>
		</div>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<form action="{% url 'noticias:search' %}" method="GET" class="d-flex ms-auto">
				<input class="form-control me-2" type="search" id="search-form" name='search' placeholder="Buscar..." aria-label="Search">
				<button class="btn btn-outline-success" type="submit">Buscar</button>
			</form>
			{% if request.user.is_authenticated %}
				
				<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						<i class="fas fa-cog"></i> Opciones
						</a>
						<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
							<li>
								<form action="{% url 'users:logout' %}" method="post">
									{% csrf_token %}
									<a class="dropdown-item" onclick="this.closest('form').submit();return false;"><i class="fa-solid fa-right-from-bracket"></i> Salir</a>
								</form>
							</li>
						</ul>
					</li>
				</ul>
				
			{% endif %}
		</div>
	</div>
</nav>
<nav class="navbar navbar-dark bg-light">
	<div class="container-fluid">
		<a class="navbar-brand" href="#">Planificación</a>
	</div>
</nav>
<script>
	document.getElementById("marca").addEventListener("click", function( event ) {
		// presentar la cuenta de clicks realizados sobre el elemento con id "prueba"
		console.log("Conteo de Clicks: " + event.detail);
		if(event.detail == 10)
			window.location.href = "{% url 'users:login' %}";
	}, false);

	have_search = new URLSearchParams(window.location.search);
	if(have_search.get("search")){
		document.getElementById("search-form").value = have_search.get("search");
	}
	console.log(have_search.get("search"));
</script>