apps/noticias/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    path('', Main, name='main'),
    path('nosotros/', nosotros, name='nosotros'),
    path('constance/', login_required(CosntanceView.as_view()), name='constance'),

    path('publicacion/<int:pk>/', publicacion_view, name='publicacion'),
    path('createpublicaion/', login_required(CreatePublicacionView.as_view()), name='create_publicacion'),
    path('updatepublicaion/<int:pk>/', login_required(UpdatePublicaionView.as_view()), name='update_publicaion'),
    path('listpublicacion/', login_required(ListPublicacionView.as_view()), name='list_publicacion'),
    path('archivoinline/<int:pk>/', login_required(archivo_inline_view), name='archivo_inline'),
    path('search/', ListPublicacionBusquedaView.as_view(), name='search'),

    path('listpaginas/', login_required(ListPaginasView.as_view()), name='list_paginas'),
    path('createpagina/', login_required(CreatePaginaView.as_view()), name='create_pagina'),
    path('updatepagina/<int:pk>/', login_required(UpdatePaginaView.as_view()), name='update_pagina'),

    path('listtipo/', login_required(ListTiposView.as_view()), name='list_tipo'),
    path('createtipo/', login_required(CreateTipoView.as_view()), name='create_tipo'),
    path('updatetipo/<int:pk>/', login_required(UpdateTipoView.as_view()), name='update_tipo'),

    path('listdepartemento/', login_required(ListDepartamentoView.as_view()), name='list_departamento'),
    path('creardeparatmento/', login_required(CreateDepartamentoView.as_view()), name='create_departamento'),
    path('updatedepartamento/<int:pk>/', login_required(UpdateDepartamentoView.as_view()), name='update_departamento'),

    path('listautoridades/', login_required(ListAutoridadesView.as_view()), name='list_autoridades'),
    path('createautoridades/', login_required(CreateAutoridadesView.as_view()), name='create_autoridaes'),
    path('updateautoridaes/<int:pk>/', login_required(UpdateAutoridadesView.as_view()), name='update_autoridades'),

    path('listfiltropublicacion/<int:pk>/', ListPublicacionFiltroBusquedaView.as_view(), name='list_filtro_publicacion')
]

planipage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.urls import reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(url=reverse_lazy('noticias:main')), name='home'),
    path('noticias/', include(('apps.noticias.urls','noticias'), namespace='noticias')),
    path('users/', include(('apps.users.urls','users'), namespace='users')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/noticias/models.py
from django.db import models
from django.db.models import Q

# Create your models here.

class Autoridades(models.Model):
	nombre = models.CharField(
		max_length=500,
		null=False,
		blank=False
	)
	cargo = models.CharField(
		max_length=500
	)
	prioridad = models.FloatField(
		null=False,
		blank=False,
		default=1
	)
	class Meta:
		ordering = ['prioridad','id']
	def __str__(self):
		return self.nombre

class Pagina(models.Model):
	nombre = models.CharField(
		null=False,
		blank=False,
		max_length=200
	)
	url = models.URLField(
		null=False,
		blank=False
	)
	def __str__(self):
		return self.nombre

class Departamento(models.Model):
	nombre = models.CharField(
		null=False,
		blank=False,
		max_length=200
	)
	prioridad = models.FloatField(
		null=False,
		blank=False,
		default=1
	)
	destacar = models.BooleanField(
		null=False,
		blank=False,
		default=False
	)
	class Meta:
		ordering = ['prioridad','id']
	def tipos_get(self):
		return Tipo.objects.filter(departamento=self)
	def __str__(self):
		return self.nombre

class Tipo(models.Model):
	departamento = models.ForeignKey('noticias.Departamento', on_delete=models.CASCADE)
	tipo = models.CharField(
		null=False,
		blank=False,
		max_length=300
	)
	prioridad = models.FloatField(
		null=False,
		blank=False,
		default=1
	)
	class Meta:
		ordering = ['prioridad','id']
	def __str__(self):
		return str(self.departamento) + ' - ' + self.tipo

class Publicacion(models.Model):
	tipo = models.ManyToManyField('noticias.Tipo')
	nombre = models.CharField(
		null=False,
		blank=False,
		max_length=500
	)
	resumen = models.CharField(
		null=True,
		blank=True,
		max_length=500
	)
	contenido = models.TextField(
		null=False,
		blank=False
	)
	publicar = models.BooleanField(
		null=False,
		blank=False,
		default=False
	)
	creado = models.DateTimeField(
		null=False,
		blank=False,
		auto_now_add=True,
	)
	modificado = models.DateTimeField(
		null=False,
		blank=False,
		auto_now=True,
	)
	def solo_fotos(self):
		return Archivo.objects.filter(Q(archivo__icontains='.jpeg')|Q(archivo__icontains='.jpg')|Q(archivo__icontains='.png'), publicacion=self)
	def archivos(self):
		return Archivo.objects.filter(~(Q(archivo__icontains='.jpeg')|Q(archivo__icontains='.jpg')|Q(archivo__icontains='.png')),  publicacion=self)
	def __str__(self):
		return self.nombre

class Archivo(models.Model):
	publicacion = models.ForeignKey('noticias.Publicacion', on_delete=models.CASCADE)
	archivo = models.FileField(
		upload_to='archivos/%Y-%m-%d-%H-%i-%s-%u/',
		null=False,
		blank=False
	)
	prioridad = models.FloatField(
		null=False,
		blank=False,
		default=1
	)
	def __str__(self):
		return str(self.publicacion)

apps/noticias/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from constance import config
from django.conf import settings
from .models import *

class SearchForm(forms.Form):
	search = forms.CharField(required=False, label="", help_text="", widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Buscar...','autocomplete':'off'}))

class PublicacionForm(forms.ModelForm):
	class Meta:
		model = Publicacion
		fields = '__all__'
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['contenido'].required = False

archivos_inline_form = inlineformset_factory(Publicacion, Archivo, exclude=[''], extra=1, can_delete=True)

class PaginaForm(forms.ModelForm):
	class Meta:
		model = Pagina
		exclude = ['']

class TipoForm(forms.ModelForm):
	class Meta:
		model = Tipo
		exclude = ['']

class DepartemanetoForm(forms.ModelForm):
	class Meta:
		model = Departamento
		exclude = ['']

class AutoridadesForm(forms.ModelForm):
	class Meta:
		model = Autoridades
		exclude = ['']

class ArchivosHelperForm(FormHelper):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.form_method = 'post'
		self.layout = Layout(
			Row(
				Column('archivo'),
				Column('prioridad'),
				css_class='g-1'
			)
		)
		self.render_required_fields = True
		self.form_tag = False

class ConstanceForm(forms.Form):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for key in self.Meta.constance_values.keys():
			data = self.Meta.constance_values[key]
			typo = self.getDataOrNone(data,2)
			if not typo or typo==str:
				self.fields[key] = forms.CharField(widget=forms.Textarea(),label=data[1], required=False, initial=getattr(self.Meta.constance,key))
			elif(typo==bool):
				self.fields[key] = forms.BooleanField(label=data[1], required=True, initial=getattr(self.Meta.constance,key))
			elif(typo==int):
				self.fields[key] = forms.IntegerField(label=data[1], required=True, initial=getattr(self.Meta.constance,key))
			elif(typo==float):
				self.fields[key] = forms.FloatField(label=data[1], required=True, initial=getattr(self.Meta.constance,key))
	def getDataOrNone(self, data, index):
		try:
			return data[index]
		except Exception as e:
			return None
	def save(self):
		for key in self.cleaned_data:
			setattr(self.Meta.constance, key, self.cleaned_data[key])
	class Meta:
		constance = config
		constance_values = settings.CONSTANCE_CONFIG

apps/noticias/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, CreateView, UpdateView, FormView, DeleteView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from .generic import *
from .forms import *
from .models import *
from constance import config

# Create your views here.

def Main(request):
	publicaciones = Publicacion.objects.filter(publicar=True).prefetch_related('archivo_set','tipo','tipo__departamento').order_by('-id')[:20]
	return render(request,'main.html', {'publicaciones':publicaciones})

def nosotros(request):
	autoridades = Autoridades.objects.all()
	return render(request, 'nosotros.html',{'autoridades':autoridades,'config':config})

def publicacion_view(request, pk):
	noticia = Publicacion.objects.prefetch_related('archivo_set').get(id=pk)
	return render(request, 'publicacion.html',{'noticia':noticia})

class CreatePublicacionView(CreateView):
	form_class = PublicacionForm
	template_name = 'publicacion/create_publicacion.html'
	success_url = 'noticias:archivo_inline'
	def get_success_url(self):
		return reverse_lazy(self.success_url, kwargs={'pk':self.object.id})

class UpdatePublicaionView(UpdateView):
	model = Publicacion
	form_class = PublicacionForm
	template_name = 'publicacion/update_publicacion.html'
	success_url = 'noticias:archivo_inline'
	def get_success_url(self):
		return reverse_lazy(self.success_url, kwargs={'pk':self.object.id})

class ListPublicacionView(ListSearchView):
	model = Publicacion
	paginate_by = 10
	template_name = 'publicacion/list_publicaion.html'
	fields_search = ['id','nombre','tipo','publicar']

def archivo_inline_view(request, pk):
	instance = get_object_or_404(Publicacion, id=pk)
	fom_inline = archivos_inline_form
	helper = ArchivosHelperForm()
	if request.method == 'POST':
		formset = fom_inline(request.POST, request.FILES, instance=instance)
		if formset.is_valid():
			formset.save()
			if 'add' in request.POST:
				return HttpResponseRedirect(request.path)
			else:
				return HttpResponseRedirect(reverse_lazy('noticias:list_publicacion'))
	else:
		formset = fom_inline(instance=instance)
	return render(request, 'publicacion/archivos_inline.html',{'formset':formset, 'helper':helper, 'instance':instance})

class ListPublicacionBusquedaView(ListSearchView):
	model = Publicacion
	paginate_by = 10
	template_name = 'publicacion/list_publicaion_search.html'
	fields_search = ['nombre']
	def get_queryset(self):
		return super().get_queryset().filter(publicar=True).distinct()

class ListPaginasView(ListSearchView):
	model = Pagina
	paginate_by = 10
	template_name = 'paginas/list_paginas.html'
	fields_search = ['id','nombre','url']

class CreatePaginaView(CreateView):
	form_class = PaginaForm
	template_name = 'paginas/create_paginas.html'
	success_url = reverse_lazy('noticias:list_paginas')

class UpdatePaginaView(UpdateView):
	model = Pagina
	form_class = PaginaForm
	template_name = 'paginas/update_pagina.html'
	success_url = reverse_lazy('noticias:list_paginas')

#tipos
class ListTiposView(ListSearchView):
	model = Tipo
	paginate_by = 10
	template_name = 'tipo/list_tipos.html'
	fields_search = ['id','tipò']

class CreateTipoView(CreateView):
	form_class = TipoForm
	template_name = 'tipo/create_tipo.html'
	success_url = reverse_lazy('noticias:list_tipo')

class UpdateTipoView(UpdateView):
	model = Tipo
	form_class = TipoForm
	template_name = 'tipo/update_tipo.html'
	success_url = reverse_lazy('noticias:list_tipo')

#Departamento
class ListDepartamentoView(ListSearchView):
	model = Departamento
	paginate_by = 10
	template_name = 'departamento/list_departamento.html'
	fields_search = ['id','tipo']

class CreateDepartamentoView(CreateView):
	form_class = DepartemanetoForm
	template_name = 'departamento/create_departamento.html'
	success_url = reverse_lazy('noticias:list_departamento')

class UpdateDepartamentoView(UpdateView):
	model = Departamento
	form_class = DepartemanetoForm
	template_name = 'departamento/update_departamento.html'
	success_url = reverse_lazy('noticias:list_departamento')

#lista filtrada
class ListPublicacionFiltroBusquedaView(ListSearchView, ModelExtraView):
	model_extra = Tipo
	model = Publicacion
	paginate_by = 10
	template_name = 'publicacion/list_publicaion_filtro_search.html'
	fields_search = ['id','nombre','tipo','publicar']
	def get_queryset(self):
		query = super().get_queryset().filter(publicar=True, tipo__id=self.kwargs['pk']).order_by('-id')
		return self.search_fields(query)

#Autoridades
class ListAutoridadesView(ListSearchView):
	model = Autoridades
	paginate_by = 10
	template_name = 'autoridades/list_autoridades.html'
	fields_search = ['id','nombre']

class CreateAutoridadesView(CreateView):
	form_class = AutoridadesForm
	template_name = 'autoridades/create_autoridades.html'
	success_url = reverse_lazy('noticias:list_autoridades')

class UpdateAutoridadesView(UpdateView):
	model = Autoridades
	form_class = AutoridadesForm
	template_name = 'autoridades/update_autoridades.html'
	success_url = reverse_lazy('noticias:list_autoridades')

class CosntanceView(FormView):
	form_class = ConstanceForm
	template_name = 'constance.html'
	success_url = '/'
	def form_valid(self, form):
		if form.is_valid():
			form.save()
		return super().form_valid(form)

apps/noticias/templates/publicacion/archivos_inline.html
{% extends "base/base_form.html" %}
{% load crispy_forms_tags %}
	{% block name %}
		<h2 class="text-center">Archivo</h2>
	{% endblock name %}

	{% block bodyform %}
		<form action="" method="post" class="form" enctype="multipart/form-data">
			
			{% csrf_token %}
			{% crispy formset helper %}

			<div class="d-flex justify-content-center">
				<div class="btn-group" role="group" aria-label="Basic example">
					<button name="add" class="btn btn-primary">Guardar y Añadir Otro</button>
		    		<button type="submit" class="btn btn-primary">Enviar</button>
		    	</div>
			</div>
		</form>
	{% endblock bodyform %}

apps/noticias/templates/publicacion/create_publicacion.html
{% extends "base/base_form.html" %}
{% load crispy_forms_tags %}
	{% block name %}
		<h2 class="text-center">Crear Publicacion</h2>
	{% endblock name %}
	{% block bodyform %}

		<form action="" method="post" class="form">
			{% csrf_token %}
			{{ form|crispy }}
			
			<div class="d-flex justify-content-center">
		    	<button type="submit" class="btn btn-primary">Enviar</button>
			</div>
			
		</form>
		
	{% endblock bodyform %}

	{% block scripts %}
		<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'advlist link image lists',
			language: 'es',
			plugins: [
				'advlist', 'autolink', 'lists', 'link', 'image', 'charmap', 'preview',
				'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
				'insertdatetime', 'media', 'table', 'help', 'wordcount'
			],
		});
		</script>
	{% endblock scripts %}

apps/noticias/templates/publicacion/list_publicaion.html
{% extends "base/base_list.html" %}
	{% block name %}
		<h2 class="text-center">Lista de Publicaciones</h1>
	{% endblock name %}

	{% block bodylist %}
		<form method="GET" action="" class="pb-3">
			{{form}}
			<button type="submit" class="no-show">Enviar</button>
		</form>
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Nombre</th>
					<th scope="col">Tipo</th>
					<th scope="col">Publicado?</th>
					<th scope="col">Creado</th>
					<th scope="col">Modificado</th>
					<th scope="col">Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for object in object_list %}
					<tr>
						<th>{{ object.id }}</th>
						<td>{{ object.nombre }}</td>
						<td>
							{% for tipo in object.tipo.all %}
								<span class="badge bg-primary">{{ tipo.tipo }}</span>
								{% if not forloop.last %}
									<br>
								{% endif %}
							{% endfor %}
						</td>
						<td>
							{% if object.publicar %}
								<span class="badge bg-success">Publicado</span>
							{% else %}
								<span class="badge bg-danger">No Publicado</span>
							{% endif %}
						</td>
						<td>{{ object.creado|date:"d/M/Y" }}</td>
						<td>{{ object.modificado|date:"d/M/Y" }}</td>
						<td>
							<div class="dropdown">
								<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
								Opciones
								</button>
								<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
									<li><a class="dropdown-item" href="{% url 'noticias:update_publicaion' object.id %}"> Actualizar</a></li>
									<li><a class="dropdown-item" href="{% url 'noticias:archivo_inline' object.id %}"><i class="fas fa-key"></i> Archivos</a></li>
								</ul>
							</div>
						</td>	
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% endblock bodylist %}

apps/noticias/templates/publicacion/list_publicaion_filtro_search.html
{% extends "publicacion/list_publicaion_search.html" %}
	{% block name %}
		<h1 class="text-center">{{ object_extra.departamento.nombre }} - {{ object_extra.tipo }}</h1>
	{% endblock name %}

apps/noticias/templates/publicacion/list_publicaion_search.html
{% extends "base/base_list.html" %}
{% load crispy_forms_tags %}
	{% block name %}
		<h2 class="text-center">Resultados</h2>
	{% endblock name %}

	{% block bodylist %}
		<div class="container text-center">
			<div class="row justify-content-center gy-2 gx-2">
				{% for p in object_list %}
					<div class=" col-sm-12 col-xl-4">
						<div class="card" style="height: 100%;">
							<img class="img-search auto-img" src="{{ p.solo_fotos.0.archivo.url }}" class="card-img-top" alt="...">
							<div class="card-body">
								<h6 class="card-title">{{ p.nombre }}</h6>
								<p class="card-text">{{ p.resumen }}</p>

								<div>
									
									<p>
									<b>Tipo:</b>
									{% for tipo in p.tipo.all %}
										<span class="badge bg-primary" style="font-size:0.6rem">{{ tipo.tipo }}</span>
									{% endfor %}
									</p>
								</div>
								<a href="{% url 'noticias:publicacion' p.pk %}" class="stretched-link"></a>
							</div>
						</div>
					</div>
					
				{% empty %}
					<div class="card col" style="width: 100%;">
						<h3 class="text-center">Aun no existen publicaciones</h3>
					</div>
				{% endfor %}
			</div>
		</div>
		<br>
	{% endblock bodylist %}

apps/noticias/templates/publicacion/update_publicacion.html
{% extends "publicacion/create_publicacion.html" %}
	{% block name %}
		<h2 class="text-center">Actualizar Archivo</h2>
	{% endblock name %}